### ISSUE TITLE
Effect runs multiple times even when `Deps::none()` is used

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [yishn/wasm-react#12]
When using `wasm-react`, it results in the error `Too many re-renders. React limits the number of renders to prevent an infinite loop.`. [Repro](https://github.com/ChocolateLoverRaj/was-react-bug). This doesn't happen in [equivalent JS code](https://stackblitz.com/edit/stackblitz-starters-8yfhzb?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js&title=React%20Starter).

```rs
use wasm_react::{
    clones, h,
    hooks::{use_effect, use_state, Deps},
    Component, VNode,
};

pub struct Counter;
impl Component for Counter {
    fn render(&self) -> VNode {
        let counter = use_state(|| false);

        use_effect(
            {
                clones!(mut counter);
                counter.set(|mut _counter| true);

                move || || ()
            },
            Deps::none(),
        );

        h!(div).build("<Component />")
    }
}
``` 
Using `v0.6`

**Comment by ChocolateLoverRaj** [comment]
I tried it with `v0.5` and i get the same error

**Comment by yishn** [comment]
@ChocolateLoverRaj You're using `use_effect` wrong, please take a look [at the documentation](https://docs.rs/wasm-react/latest/wasm_react/hooks/fn.use_effect.html) or [in our discussion](https://github.com/yishn/wasm-react/discussions/10#discussioncomment-7692076).
